"""
bmd_ble — Blackmagic BLE Camera Control Framework
"""
from .constants import (
    GENERIC_ACCESS_PROFILE_SERVICE_UUID, GAP_CHARACTERISTIC_DEVICE_NAME,
    GAP_CHARACTERISTIC_APPEARANCE,
    BMD_SERVICE_UUID, CHARACTERISTIC_OUTGOING,
    CHARACTERISTIC_INCOMING,
    CHARACTERISTIC_TIMECODE, CHARACTERISTIC_CAM_STATUS, CHARACTERISTIC_BMD_DEVICE_NAME,
    CHARACTERISTIC_PROTO_VER, CHARACTERISTIC_MANUFACTURER_INFO,
    CHARACTERISTIC_MODEL_INFO, CHARACTERISTIC_NAMES, BLE_SCAN_TIMEOUT_S
)
from .camera_profile import (
    CameraProfile, KNOWN_PROFILES,
)
