"""
bmd_ble — Blackmagic BLE Camera Control Framework
"""

from .camera_profile import (
    KNOWN_PROFILES,
    CameraProfile,
    get_profile,
)
from .constants import (
    BLE_SCAN_TIMEOUT_S,
    BMD_SERVICE_UUID,
    CHARACTERISTIC_BMD_DEVICE_NAME,
    CHARACTERISTIC_CAM_STATUS,
    CHARACTERISTIC_INCOMING,
    CHARACTERISTIC_MANUFACTURER_INFO,
    CHARACTERISTIC_MODEL_INFO,
    CHARACTERISTIC_NAMES,
    CHARACTERISTIC_OUTGOING,
    CHARACTERISTIC_PROTO_VER,
    CHARACTERISTIC_TIMECODE,
    GAP_CHARACTERISTIC_APPEARANCE,
    GAP_CHARACTERISTIC_DEVICE_NAME,
    GENERIC_ACCESS_PROFILE_SERVICE_UUID,
)

__all__ = [
    "BLE_SCAN_TIMEOUT_S",
    "BMD_SERVICE_UUID",
    "CameraProfile",
    "CHARACTERISTIC_BMD_DEVICE_NAME",
    "CHARACTERISTIC_CAM_STATUS",
    "CHARACTERISTIC_INCOMING",
    "CHARACTERISTIC_MANUFACTURER_INFO",
    "CHARACTERISTIC_MODEL_INFO",
    "CHARACTERISTIC_NAMES",
    "CHARACTERISTIC_OUTGOING",
    "CHARACTERISTIC_PROTO_VER",
    "CHARACTERISTIC_TIMECODE",
    "GAP_CHARACTERISTIC_APPEARANCE",
    "GAP_CHARACTERISTIC_DEVICE_NAME",
    "GENERIC_ACCESS_PROFILE_SERVICE_UUID",
    "KNOWN_PROFILES",
    "get_profile",
]
